### ISSUE TITLE
Create Vendor Submission From

### ISSUE THREAD

**Issue by pvenkateshnaidu** [tirumalasrija/AngularDemoWok#8]
![https-portal-webmobilez-com-superadmin-sumissioncreate](https://user-images.githubusercontent.com/19386308/108029188-0eede400-7053-11eb-8d97-9c7bafe5cd5f.png)
![https-portal-webmobilez-com-superadmin-sumissioncreate (2)](https://user-images.githubusercontent.com/19386308/108037120-2632ce80-705f-11eb-8ce6-ea905d34834c.png)
![https-portal-webmobilez-com-superadmin-sumissioncreate (3)](https://user-images.githubusercontent.com/19386308/108037128-292dbf00-705f-11eb-9773-49c4754a4895.png)

**Comment by vidhyasagarreddy** [comment]
This issue is now fixed and code is merged from fixes/vendor-submission-form to main branch
